//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraductorSoftcatala.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraductorSoftcatala.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to.
        /// </summary>
        public static string Agraiments {
            get {
                return ResourceManager.GetString("Agraiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traductor Softcatalà.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apps.bitsdelocos.es/en/TraductorSoftcatala.
        /// </summary>
        public static string AppPrivacyURL {
            get {
                return ResourceManager.GetString("AppPrivacyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan ⇒ English.
        /// </summary>
        public static string ca_en {
            get {
                return ResourceManager.GetString("ca_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan ⇒ Spanish.
        /// </summary>
        public static string ca_es {
            get {
                return ResourceManager.GetString("ca_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan ⇒ French.
        /// </summary>
        public static string ca_fr {
            get {
                return ResourceManager.GetString("ca_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalan ⇒ Portuguese.
        /// </summary>
        public static string ca_pt {
            get {
                return ResourceManager.GetString("ca_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate to.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English ⇒ Catalan.
        /// </summary>
        public static string en_ca {
            get {
                return ResourceManager.GetString("en_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish ⇒ Catalan.
        /// </summary>
        public static string es_ca {
            get {
                return ResourceManager.GetString("es_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French ⇒ Catalan.
        /// </summary>
        public static string fr_ca {
            get {
                return ResourceManager.GetString("fr_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have Internet connection.
        /// </summary>
        public static string InternetNecesario {
            get {
                return ResourceManager.GetString("InternetNecesario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Languages.
        /// </summary>
        public static string Llenguatges {
            get {
                return ResourceManager.GetString("Llenguatges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese ⇒ Catalan.
        /// </summary>
        public static string pt_ca {
            get {
                return ResourceManager.GetString("pt_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error recognizing your voice..
        /// </summary>
        public static string SpeechError {
            get {
                return ResourceManager.GetString("SpeechError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to accept the speech privacy policy in order to use speech recognition in this app..
        /// </summary>
        public static string SpeechPrivacy {
            get {
                return ResourceManager.GetString("SpeechPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text for translate.
        /// </summary>
        public static string TextTraduir {
            get {
                return ResourceManager.GetString("TextTraduir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated text.
        /// </summary>
        public static string TextTraduit {
            get {
                return ResourceManager.GetString("TextTraduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        public static string Tradueix {
            get {
                return ResourceManager.GetString("Tradueix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string TxtAbout {
            get {
                return ResourceManager.GetString("TxtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string TxtContacto {
            get {
                return ResourceManager.GetString("TxtContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        public static string TxtInfo {
            get {
                return ResourceManager.GetString("TxtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        public static string TxtLegal {
            get {
                return ResourceManager.GetString("TxtLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string TxtPrivacidad {
            get {
                return ResourceManager.GetString("TxtPrivacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of service.
        /// </summary>
        public static string TxtTerminos {
            get {
                return ResourceManager.GetString("TxtTerminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string TxtVersion {
            get {
                return ResourceManager.GetString("TxtVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Valencian variant.
        /// </summary>
        public static string Valencia {
            get {
                return ResourceManager.GetString("Valencia", resourceCulture);
            }
        }
    }
}
